import type { Tool } from '../data'

export interface FaqItem {
  question: string
  answer: string
}

export const TOOL_SPECIFIC_FAQS: Record<string, FaqItem[]> = {
  'pdf-to-ppt': [
    {
      question: 'How do I convert a PDF to PowerPoint for free?',
      answer:
        'Simply upload your PDF file to ToolNest, review the slide deck layout in the interactive previewer, and click "Download PowerPoint (.pptx)". The file will download immediately with no fee and no signup.',
    },
    {
      question: 'Can I edit the text in the converted PowerPoint presentation?',
      answer:
        'Yes! ToolNest generates genuine Microsoft PowerPoint OpenXML (.pptx) presentation files with editable text boxes, titles, and bullet points. You can change words, adjust fonts, add animations, and modify formatting in Microsoft PowerPoint or Google Slides.',
    },
    {
      question: 'Is my confidential PDF file safe?',
      answer:
        'Yes, completely. ToolNest runs client-side inside your browser engine. Your files are not uploaded to our servers, stored in databases, or reviewed by anyone. Once you close your browser tab, memory is cleared.',
    },
    {
      question: 'Does the converted presentation work on Mac and Google Slides?',
      answer:
        'Yes. The generated .pptx format is universally compliant with Microsoft Office 365, PowerPoint 2016-2024, Google Slides, Apple Keynote on macOS / iOS, and LibreOffice Impress on Linux.',
    },
    {
      question: 'Can I choose between 16:9 widescreen and 4:3 standard slides?',
      answer:
        'Yes. ToolNest provides a quick slide ratio toggle so you can create modern 16:9 widescreen presentations for modern displays, or 4:3 standard slides for classic conference projectors.',
    },
  ],
  'pdf-compressor': [
    {
      question: 'How do I reduce PDF file size without losing quality?',
      answer:
        'Select your PDF in ToolNest PDF Compressor and choose your desired compression level (Basic, Recommended, or Maximum). The tool optimizes document streams and images directly in your browser.',
    },
    {
      question: 'How much can my PDF file size be reduced?',
      answer:
        'Depending on the document composition and embedded images, file size can typically be reduced by 30% to over 60% while maintaining crisp vector text and readable graphics.',
    },
    {
      question: 'Does PDF compression upload my documents to the cloud?',
      answer:
        'No. ToolNest processes PDF files locally in your browser session using web standards. No document data leaves your device.',
    },
    {
      question: 'Is there a file size limit or fee for compressing PDFs?',
      answer:
        'No. ToolNest PDF Compressor is completely free with no document quotas, subscription paywalls, or hidden charges.',
    },
  ],
  'pdf-merger': [
    {
      question: 'How do I combine multiple PDF files into one document?',
      answer:
        'Upload two or more PDF documents into ToolNest PDF Merger, arrange them in your preferred sequence, and click "Merge PDFs" to download a single combined PDF file.',
    },
    {
      question: 'Can I reorder or delete files before merging?',
      answer:
        'Yes. You can review all selected files in the sequence list and remove or add documents before generating your final merged file.',
    },
    {
      question: 'Will merging PDFs preserve original document formatting and bookmarks?',
      answer:
        'Yes. Document pages, text formatting, and image resolutions are preserved intact in the merged output document.',
    },
    {
      question: 'Is there a limit on how many PDF files I can merge?',
      answer:
        'You can merge multiple PDFs at once without artificial limits or mandatory registration.',
    },
  ],
  'pdf-splitter': [
    {
      question: 'How do I extract specific pages from a PDF?',
      answer:
        'Upload your PDF file to ToolNest PDF Splitter, enter your desired page range (for example "1-3, 5, 8-10"), and click "Extract Selected Pages" to save them as a new PDF.',
    },
    {
      question: 'Can I split non-consecutive pages into a new document?',
      answer:
        'Yes. You can specify single pages, ranges, or custom commas-separated combinations to extract precisely the pages you need.',
    },
    {
      question: 'Does ToolNest add watermarks to split PDF pages?',
      answer:
        'No. All documents generated by ToolNest are 100% clean and free of watermarks or advertising stamps.',
    },
  ],
  'pdf-to-jpg': [
    {
      question: 'How do I convert PDF pages into high-resolution JPG images?',
      answer:
        'Upload your PDF document to ToolNest PDF to JPG converter and click "Download as .JPG". Each page is rendered at high resolution for easy sharing.',
    },
    {
      question: 'Can I convert multi-page PDFs to JPG images?',
      answer:
        'Yes. You can convert individual pages or complete document sets into sharp, ready-to-share JPEG images.',
    },
    {
      question: 'Are converted JPG photos ready to share on social media or email?',
      answer:
        'Yes. The exported JPG files are standard JPEG images compatible with all image viewers, email clients, presentations, and social platforms.',
    },
  ],
  'jpg-to-pdf': [
    {
      question: 'How do I convert multiple JPG and PNG images into a PDF?',
      answer:
        'Select or drag and drop your photos into ToolNest JPG to PDF tool, reorder the pages using the up/down arrows, select orientation (Portrait/Landscape) and page size (A4/Letter), then click "Convert to PDF".',
    },
    {
      question: 'Can I change the order of images before generating the PDF?',
      answer:
        'Yes. The visual card grid allows you to easily move pages up, move them down, or remove individual images before creating the document.',
    },
    {
      question: 'Can I choose between A4 and US Letter page sizes?',
      answer:
        'Yes. ToolNest lets you choose between A4 standard and US Letter page formats with automatic proportional image centering.',
    },
  ],
  'image-compressor': [
    {
      question: 'How does client-side image compression work?',
      answer:
        'ToolNest utilizes HTML5 Canvas and browser image processing algorithms to optimize image encoding quality without uploading your photo to any third-party server.',
    },
    {
      question: 'What image formats can I compress with ToolNest?',
      answer:
        'ToolNest Image Compressor supports JPG, PNG, and WebP image formats with real-time compression ratio preview.',
    },
    {
      question: 'Will compressing an image reduce its dimensions?',
      answer:
        'No. Image compression optimizes pixel data and file encoding while retaining the original pixel dimensions (width and height). Use Image Resizer if you wish to change dimensions.',
    },
    {
      question: 'How much file size reduction can I expect?',
      answer:
        'Depending on the source image and quality slider setting (10% to 95%), you can typically reduce image file size by 40% to 80% with minimal visual difference.',
    },
  ],
  'image-resizer': [
    {
      question: 'How do I resize an image to specific pixel dimensions?',
      answer:
        'Upload your image, type your target width or height in pixels, and click Download. The tool resizes the image instantly using high-quality bicubic resampling.',
    },
    {
      question: 'Can I lock the aspect ratio while resizing?',
      answer:
        'Yes. The "Maintain aspect ratio lock" checkbox ensures that changing width automatically updates height proportionally so your image never looks stretched or squished.',
    },
    {
      question: 'Does ToolNest resize photos without quality loss?',
      answer:
        'Yes. The canvas renderer applies anti-aliasing and smoothing algorithms to ensure resized graphics remain sharp.',
    },
  ],
  'jpg-to-png': [
    {
      question: 'How do I convert a JPG picture to PNG format?',
      answer:
        'Upload your JPG file to ToolNest JPG to PNG converter and click Download as .PNG. The conversion executes instantly in your browser.',
    },
    {
      question: 'Why should I convert JPG to PNG?',
      answer:
        'PNG uses lossless compression, making it ideal for graphics, text screenshots, illustrations, and logos where sharp edges and no compression artifacts are required.',
    },
  ],
  'png-to-jpg': [
    {
      question: 'How do I convert a PNG image to JPG?',
      answer:
        'Upload your PNG file and click Download as .JPG. The tool renders the image against a clean white background and exports a lightweight JPG file.',
    },
    {
      question: 'Why is a JPG image file size smaller than PNG?',
      answer:
        'JPG uses specialized lossy compression tuned for photographic color palettes, resulting in significantly smaller file sizes that load faster on web pages.',
    },
  ],
  'webp-converter': [
    {
      question: 'What are the benefits of converting images to WebP?',
      answer:
        'WebP is a modern web image format developed by Google that provides superior lossless and lossy compression, reducing image file sizes by 25% to 35% compared to JPG/PNG at equivalent quality.',
    },
    {
      question: 'Are WebP images supported in all web browsers?',
      answer:
        'Yes. All modern browsers including Google Chrome, Apple Safari, Mozilla Firefox, Microsoft Edge, and mobile browsers fully support WebP images.',
    },
  ],
  'image-cropper': [
    {
      question: 'How do I crop an image online for free?',
      answer:
        'Upload your image to ToolNest Image Cropper, adjust your desired dimensions or boundary, and download the cropped photo immediately.',
    },
    {
      question: 'Does cropping reduce photo clarity?',
      answer:
        'No. The cropped area retains its exact original native resolution and pixel clarity.',
    },
  ],
  'word-counter': [
    {
      question: 'How does the ToolNest Word Counter calculate words and characters?',
      answer:
        'The tool parses text streams in real time, calculating word counts by whitespace boundaries, characters with spaces, characters without spaces, sentences, and paragraphs.',
    },
    {
      question: 'How are reading time and speaking time estimated?',
      answer:
        'Reading time is calculated at an average reading speed of 200 words per minute (WPM), while speaking time is calculated at 130 words per minute (standard speech presentation rate).',
    },
    {
      question: 'Is my pasted text private and secure?',
      answer:
        'Yes. Everything is processed locally in your browser memory. No text is ever transmitted over the network or saved.',
    },
  ],
  'character-counter': [
    {
      question: 'What is the difference between total characters and characters without spaces?',
      answer:
        'Total characters include every letter, number, punctuation mark, and space. Characters without spaces exclude whitespace, which is essential for certain academic submissions and character-restricted forms.',
    },
    {
      question: 'Why is character counting important for social media?',
      answer:
        'Platforms like X (formerly Twitter) have a 280-character limit, while Meta, LinkedIn, and SMS messaging have strict length cutoffs. The character counter lets you preview and refine copy before publishing.',
    },
  ],
  'case-converter': [
    {
      question: 'What text cases can I convert between?',
      answer:
        'ToolNest Case Converter supports UPPERCASE, lowercase, Title Case, Sentence case, camelCase, kebab-case, and snake_case with a single click.',
    },
    {
      question: 'How does Title Case work in ToolNest?',
      answer:
        'Title Case capitalizes the first letter of each word in your phrase, making it ideal for article headlines, book titles, and formal documents.',
    },
  ],
  'remove-duplicate-lines': [
    {
      question: 'How do I remove duplicate lines from a text list?',
      answer:
        'Paste your lines of text into ToolNest Remove Duplicate Lines tool, select your options (trim whitespace or case-sensitive), and click "Remove Duplicates". Unique lines are returned instantly.',
    },
    {
      question: 'Can I preserve original line ordering while removing duplicates?',
      answer:
        'Yes. The first occurrence of each unique line is preserved in its original sequential order while all subsequent duplicates are stripped.',
    },
  ],
  'text-sorter': [
    {
      question: 'How can I sort text lines alphabetically?',
      answer:
        'Paste your list into ToolNest Text Sorter and click "Sort A → Z" or "Sort Z → A". You can also sort by line length, reverse the list, or randomly shuffle lines.',
    },
    {
      question: 'Does the sorter support special characters and international accents?',
      answer:
        'Yes. The sorter uses locale-aware string comparison to accurately order accented characters and multilingual alphabets.',
    },
  ],
  'lorem-ipsum-generator': [
    {
      question: 'What is Lorem Ipsum and why is it used?',
      answer:
        'Lorem Ipsum is standardized Latin dummy placeholder text used in typography, web design, and layout mockups to demonstrate visual hierarchy without distracting from content.',
    },
    {
      question: 'How many paragraphs of Lorem Ipsum can I generate?',
      answer:
        'You can generate between 1 and 10 paragraphs of natural-flowing dummy text with the option to begin with the standard "Lorem ipsum dolor sit amet..." opening.',
    },
  ],
  'percentage-calculator': [
    {
      question: 'What types of percentage calculations can I solve?',
      answer:
        'ToolNest Percentage Calculator supports three major modes: finding what X% of Y is, finding what percentage X is of Y, and calculating the percentage increase or decrease between two numbers.',
    },
    {
      question: 'Can I calculate percentage changes with decimal values?',
      answer:
        'Yes. The calculator accepts positive, negative, and decimal inputs and provides calculations rounded to two decimal places.',
    },
  ],
  'age-calculator': [
    {
      question: 'How does the age calculator determine exact age?',
      answer:
        'Select your date of birth, and ToolNest calculates your exact chronological age in years, months, and days, along with total days lived, total hours, and countdown to your next birthday.',
    },
    {
      question: 'Does the age calculator account for leap years and month lengths?',
      answer:
        'Yes. The date difference algorithms precisely handle 28, 29, 30, and 31-day months as well as leap year cycles.',
    },
  ],
  'bmi-calculator': [
    {
      question: 'How is Body Mass Index (BMI) calculated?',
      answer:
        'BMI is calculated as weight in kilograms divided by height in meters squared (kg/m²), or using imperial units via weight in pounds multiplied by 703 divided by height in inches squared.',
    },
    {
      question: 'What do the BMI score ranges mean?',
      answer:
        'According to the World Health Organization: below 18.5 is Underweight, 18.5–24.9 is Normal weight, 25.0–29.9 is Overweight, and 30.0 or above indicates Obesity.',
    },
    {
      question: 'Can I use both Metric (cm/kg) and Imperial (feet/inches/lbs) units?',
      answer:
        'Yes. ToolNest provides dedicated tabs for Metric and Imperial measurements with an interactive color-coded health gauge.',
    },
  ],
  'discount-calculator': [
    {
      question: 'How do I calculate a sale price with a percentage discount?',
      answer:
        'Enter the original item price and discount percentage. You can also specify an optional sales tax or GST percentage to see total savings and final payable price.',
    },
    {
      question: 'Can I see both the total dollars saved and final price to pay?',
      answer:
        'Yes. The calculator outputs the net discounted price, the exact dollar amount saved, and the final total including applicable tax.',
    },
  ],
  'gst-tax-calculator': [
    {
      question: 'What is the difference between GST inclusive and GST exclusive?',
      answer:
        'GST Exclusive adds the tax rate on top of your base price (Base + Tax = Total). GST Inclusive extracts the tax amount already embedded in the total retail price (Total - Tax = Base).',
    },
    {
      question: 'Which standard GST slabs can I calculate?',
      answer:
        'ToolNest offers quick preset buttons for standard tax rates (5%, 12%, 18%, 28%) along with a custom rate input for international VAT or local sales tax.',
    },
  ],
  'loan-calculator': [
    {
      question: 'How is the monthly loan EMI calculated?',
      answer:
        'The Equated Monthly Installment (EMI) is computed using the standard reducing-balance loan amortization formula based on Principal, Annual Interest Rate, and Tenure in years.',
    },
    {
      question: 'How can I minimize the total interest paid on a loan?',
      answer:
        'Selecting a shorter tenure or securing a lower interest rate significantly reduces total interest payments over the life of the loan.',
    },
  ],
  'json-formatter': [
    {
      question: 'How do I beautify and format unformatted JSON?',
      answer:
        'Paste your JSON string into ToolNest JSON Formatter and click "Format (2 Spaces)" or "Format (4 Spaces)". The tool parses the structure and formats it with readable indentation.',
    },
    {
      question: 'Can I minify JSON to reduce payload size for APIs?',
      answer:
        'Yes. Click "Minify / Compact" to strip all unnecessary whitespace and newlines, optimizing the JSON for fast network transmission.',
    },
    {
      question: 'Is my confidential JSON data safe from external servers?',
      answer:
        'Yes. All parsing and formatting occurs strictly in client-side JavaScript. No payload is sent to any server.',
    },
  ],
  'json-validator': [
    {
      question: 'How does the ToolNest JSON Validator check syntax?',
      answer:
        'Paste your code and click "Validate JSON". The validator checks bracket pairing, quotation syntax, comma placement, and data types, highlighting the exact error message if invalid.',
    },
    {
      question: 'What details are provided for valid JSON?',
      answer:
        'For valid JSON, ToolNest reports root structure type (Object or Array), top-level property count, and total payload size in bytes.',
    },
  ],
  'base64-encoder-decoder': [
    {
      question: 'What is Base64 encoding and why is it used?',
      answer:
        'Base64 encoding converts binary or text data into an ASCII string format (using A-Z, a-z, 0-9, +, /) so it can be safely transferred across protocols like HTTP, email, and JSON without corruption.',
    },
    {
      question: 'Can I decode Base64 strings back into readable text?',
      answer:
        'Yes. Switch to the "Base64 to Text (Decode)" tab, paste the encoded string, and click Decode to restore the original UTF-8 text.',
    },
  ],
  'url-encoder-decoder': [
    {
      question: 'Why do URLs need to be encoded?',
      answer:
        'Special characters (such as spaces, ampersands, question marks, and slashes) have reserved meanings in web addresses. URL encoding converts these characters into percent-encoded hex codes (%20, %26, etc.) so browsers and servers interpret parameters correctly.',
    },
    {
      question: 'Can I decode percent-encoded URLs back into plain text?',
      answer:
        'Yes. Click the "URL Decode" tab to convert percent-encoded strings back to standard readable URLs and query parameters.',
    },
  ],
  'uuid-generator': [
    {
      question: 'What is a Version 4 UUID?',
      answer:
        'A Version 4 Universally Unique Identifier (UUID) is a 128-bit identifier generated using cryptographically strong pseudo-random numbers (e.g. 550e8400-e29b-41d4-a716-446655440000).',
    },
    {
      question: 'Are the generated UUIDs truly unique?',
      answer:
        'Yes. The probability of generating a duplicate v4 UUID is so infinitesimally small (1 in 2.71 quintillion) that they are considered universally unique for software applications, databases, and APIs.',
    },
    {
      question: 'Can I generate multiple UUIDs at once?',
      answer:
        'Yes. Use the quantity slider to generate between 1 and 25 UUIDs simultaneously, with options for uppercase formatting and hyphen removal.',
    },
  ],
  'password-generator': [
    {
      question: 'How does ToolNest generate secure passwords?',
      answer:
        'ToolNest uses the browser native `crypto.getRandomValues()` API to generate cryptographically random strings that are immune to predictable pattern attacks.',
    },
    {
      question: 'What character sets can I include in my password?',
      answer:
        'You can customize passwords from 8 to 48 characters and toggle uppercase letters (A-Z), lowercase letters (a-z), numbers (0-9), and special symbols (!@#$%^&*).',
    },
    {
      question: 'Are generated passwords saved anywhere?',
      answer:
        'Never. Passwords are generated exclusively on your device in temporary memory. ToolNest has no database, telemetry, or server storage for generated passwords.',
    },
  ],
}

/**
 * Returns dynamic, tailored FAQ questions and answers for any tool.
 * Falls back to high-quality contextual questions if a tool is not explicitly listed.
 */
export function getToolFaqs(tool: Tool): FaqItem[] {
  if (TOOL_SPECIFIC_FAQS[tool.slug]) {
    return TOOL_SPECIFIC_FAQS[tool.slug]
  }

  // Contextual fallback tailored to the specific tool name and category
  return [
    {
      question: `How do I use the ${tool.name} tool on ToolNest?`,
      answer: `Using ${tool.name} is quick and straightforward. Enter or upload your input into the workspace, adjust any desired options, and get your processed result instantly with zero software installation.`,
    },
    {
      question: `Is ${tool.name} free to use?`,
      answer: `Yes, ${tool.name} is 100% free to use online on ToolNest with no registration, no subscription fees, and no usage limitations.`,
    },
    {
      question: `Does ToolNest store or upload my data when using ${tool.name}?`,
      answer: `No. ${tool.name} processes data locally in your browser engine. Your files, documents, and inputs remain private on your computer or mobile device.`,
    },
    {
      question: `Can I use ${tool.name} on mobile phones and tablets?`,
      answer: `Yes. ToolNest is fully responsive and optimized to run smoothly on desktop computers, iOS, Android, and tablets in all modern browsers.`,
    },
    {
      question: `Do I need to create an account to use ${tool.name}?`,
      answer: `No account or email address is needed. You can use ${tool.name} immediately without signing in.`,
    },
  ]
}
